from __future__ import annotations

from pydantic import BaseModel, Field


class ErrorResponse(BaseModel):
    detail: str


class MovieItem(BaseModel):
    item_id: int
    title: str
    genres: str


class HistoryResponse(BaseModel):
    user_id: int
    recent_history: list[MovieItem]


class RecommendationItem(BaseModel):
    item_id: int
    title: str
    genres: str
    score: float | None = None


class RecommendationResponse(BaseModel):
    user_id: int
    model_name: str
    recommendations: list[RecommendationItem]


class RAGResponse(BaseModel):
    user_id: int
    rationale: str = Field(description="Natural language explanation generated by the LLM.")
